###############################################
# Modify all parameters related to servoing here
###############################################
use_gazebo: true # Whether the robot is started in a Gazebo simulation environment

## Properties of incoming commands
command_in_type: "speed_units" # "unitless"> in the range [-1:1], as if from joystick. "speed_units"> cmds are in m/s and rad/s
scale:
  # Scale parameters are only used if command_in_type=="unitless"
  linear:  0.6  # Max linear velocity. Unit is [m/s]. Only used for Cartesian commands.
  rotational:  0.3 # Max angular velocity. Unit is [rad/s]. Only used for Cartesian commands.
  # Joint motion is also scaled by these factors if command_in_type=="unitless"
  joint: 0.01  # Max joint velocity. Rad/s.

## Properties of outgoing commands
publish_period: 0.034  # 1/30 Hz

# What type of topic does your robot driver expect?
# Currently supported are std_msgs/Float64MultiArray (for position/velocity controllers)
# or trajectory_msgs/JointTrajectory (for trajectory controllers)
# Note: sending trajectory_msgs/JointTrajectory is highly recommended for smooth motion
command_out_type: trajectory_msgs/JointTrajectory

# What to publish? Can save some bandwidth as most robots only require positions or velocities
publish_joint_positions: true
publish_joint_velocities: true
publish_joint_accelerations: false

## MoveIt properties
move_group_name:  parol6_arm  # Often 'manipulator' or 'arm'
planning_frame: base_link  # The MoveIt planning frame. Often 'base_link' or 'world'

## Other frames
ee_frame_name: L6  # The name of the end effector link, used to return the EE pose
robot_link_command_frame:  base_link  # commands must be given in the frame of a robot link. Usually either the base or the end effector

## Stopping behaviour
incoming_command_timeout:  0.1  # Stop servoing if X seconds elapse without a new command message
# If 0, republish commands forever even if the robot is stationary. Otherwise, specify num. to publish.
# Important because ROS may drop some messages and we need the robot to halt reliably.
num_outgoing_halt_msgs_to_publish: 4

## Configure handling of singularities and joint limits
lower_singularity_threshold:  17.0  # Start decelerating when the condition number hits this (close to singularity)
hard_stop_singularity_threshold: 30.0 # Stop when the condition number hits this
joint_limit_margin: 0.1 # added as a buffer to joint limits [radians]. If moving quickly, make this larger.

## Topic names
cartesian_command_in_topic: ~/delta_twist_cmds  # Topic for incoming Cartesian twist commands
joint_command_in_topic: ~/delta_joint_cmds # Topic for incoming joint angle commands
joint_topic: /joint_states
status_topic: ~/status
command_out_topic: /parol6_arm_controller/joint_trajectory

## Collision checking for the entire robot body
check_collisions: true # Check collisions?
collision_check_rate: 50.0 # [Hz] Collision-checking can easily bog down a CPU if done too often.
self_collision_proximity_threshold: 0.01 # Start decelerating when a self-collision is this far [m]
scene_collision_proximity_threshold: 0.05 # Start decelerating when a scene collision is this far [m]
collision_check_type: threshold_distance # Stop if a collision is closer than threshold_distance
