/servo_node:
  ros__parameters:
    move_group_name: "parol6_arm"
    command_out_topic: "/parol6_arm_controller/joint_trajectory"
    planning_frame: "link_base"
    ee_frame_name: "link_tool0"
    robot_link_command_frame: "link_base"
    
    incoming_command_topic: "/servo/delta_twist_cmds"
    incoming_joint_row_topic: "/servo/delta_joint_cmds"
    
    publish_period: 0.03
    scale:
      linear: 0.4
      rotational: 0.8
      joint: 0.5
    
    check_collisions: true
    collision_check_rate: 10.0
    collision_check_type: "threshold_distance"
    self_collision_proximity_threshold: 0.01
    scene_collision_proximity_threshold: 0.02
